springdoc:
  api-docs:
    path: /api-docs

spring:
  servlet:
    multipart:
      enabled: true

  application:
    name: sqlite

  datasource:
    url: jdbc:sqlite:mydatabase.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
