springdoc:
  api-docs:
    path: /api-docs

spring:
  servlet:
    multipart:
      enabled: true

  application:
    name: finance-tracker 
  datasource:
    url: ${SUPABASE_URL}
    # url: jdbc:sqlite:mydatabase.db
    # driver-class-name: org.sqlite.JDBC
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ddl-auto: update
      ddl-auto: none

auth:
  token: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 3600000

cookie:
  name: authToken
  expiration: 3600000
