spring:
  application:
    name: finance-app
  datasource:
    url: ${DATABASE_URL} 
    hikari:
      leak-detection-threshold: 2000 # ms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

reddit:
  api:
    client-id: ${reddit.api.client-id} 
    client-secret: ${reddit.api.client-secret} 
    user-agent: sentiment-analysis-app
    redirect-uri: http://localhost:8080/